name: Docker Build and Terraform Deploy
run-name: ${{ github.actor }} is running Terraform Deploy on ${{ github.ref_name }}
on:
  push:
    branches:
      - main
    # paths:
    #   - 'Dockerfile'
    #   - 'terraform/**'
    #   - 'ecs_pipelines/**'
    #   - 'pyproject.toml'
    #   - 'requirements.txt'
    #   - 'run.py'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          output-credentials: true
      -
        name: Deploy Container Repository
        id: containerrepo
        env:
          TF_VAR_aws_account_id: ${{ steps.creds.outputs.aws-account-id }}
          TF_VAR_image_url: ""
        run: |
          cd terraform
          terraform init -input=false
          terraform apply -target=aws_ecr_repository.image_repository -input=false -compact-warnings -auto-approve
          echo "image-url=$(terraform output -raw ecr_repo_url)\n" >> $GITHUB_OUTPUT
          cd ..
      -
        name: Build and Push Docker Container
        env:
          ECR_URL: ${{ steps.creds.outputs.aws-account-id }}.dkr.ecr.us-west-2.amazonaws.com
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_URL
          docker buildx build -t ecs-pipelines .
          docker tag ecs-pipelines:latest ${{ steps.containerrepo.outputs.image-url }}:latest
          docker push "${{ steps.containerrepo.outputs.image-url }}":latest
      -
        name: Finish Terraform Deploy
        env:
          TF_VAR_aws_account_id: ${{ steps.creds.outputs.aws-account-id }}
          TF_VAR_image_url: ${{ steps.containerrepo.outputs.image-url }}
        run: |
          cd terraform
          terraform apply -input=false -compact-warnings -auto-approve
